# Learning Goals {.unnumbered}

The goal of this course is for you to gain confidence in carrying out the entire data science pipeline, 

from research question formulation, 
to data collection/scraping,
to wrangling, 
to modeling, 
to visualization, 
to presentation and communication


Specific course topics and general skills are listed below.

## General Skills {.unnumbered}

**Data Communication**

-   In written and oral formats:

    -   Inform and justify data cleaning and analysis process and the resulting conclusions with clear, organized, logical, and compelling details that adapt to the background, values, and motivations of the audience and context in which communication occurs.

**Collaborative Learning**

-   Understand and demonstrate characteristics of effective collaboration (team roles, interpersonal communication, self-reflection, awareness of social dynamics, advocating for yourself and others).
-   Develop a common purpose and agreement on goals.
-   Be able to contribute questions or concerns in a respectful way.
-   Share and contribute to the group's learning in an equitable manner.
-   Develop a familiarity and comfort in using collaboration tools such as Git and Github. 

## Course Topics {.unnumbered}

Specific learning objectives for our course topics are listed below. Use these to guide your synthesis of course material for specific topics. Note that the topics are covered in the order of the **data science pipeline**, not the order in which we will cover them in class.

### Foundation {.unnumbered}

**Intro to R, RStudio, and R Markdown**

- Download and install the necessary tools (R, RStudio)
- Develop comfort in navigating the tools in RStudio
- Develop comfort in writing and knitting a R Markdown file
- Identify the characteristics of tidy data
- Use R code: as a calculator and to explore tidy data

<br>

### Data Acquisition {.unnumbered}

**Data Import and Basic Cleaning**

-   stuff

<br>

**Data Scraping (rvest)**

-   stuff  

<br>

**APIs**

-   stuff

<br>

**SQL**

-   stuff

### Data Wrangling {.unnumbered}

**Six main verbs**

-   stuff   

<br>


**spread/gather**

-   stuff

<br>

**join**

-   stuff 

<br>

**factors**

-   stuff 

<br>


**mini-project**

-   stuff  

<br>

### Data Visualization {.unnumbered}

*The learning goals may be adjusted before we start the material of this section.*


**Introduction to Data Visualization**

- Understand the Grammar of Graphics
- Use `ggplot2` functions to create basic layers of graphics
- Understand the different basic univariate visualizations for categorical and quantiative variables

<br>


**Effective Visualization**

- Understand and apply the guiding principles of effective visualizations


<br>

**Bivariate**

- Identify appropriate types of bivariate visualizations, depending on the type of variables (categorical, quantitative)
- Create basic bivariate visualizations based on real data with `ggplot2` functions

<br>

**Multivariate**

- Understand how we can use additional aesthetics such as color and size to incorporate a third (or more variables) to a bivariate plot with `ggplot2` functions
- Develop comfort with creating and interpreting heat maps and star plots, which allow you to look for patterns in variation in many variables. 

<br>

**Spatial**

- Plot data points on top of a map using the `ggmap()` function along with `ggplot2` functions      
- Create choropleth maps using `geom_map()`      
- Add points and other `ggplot2` features to a map created from `geom_map()`   
- Understand the basics of creating a map using `leaflet`, including adding points and choropleths to a base map 

<br>

**Network and Interactive**

-   stuff

<br>

**Shiny**

-   stuff

<br>

**Tables**

-   stuff 

<br>



### Data Modeling {.unnumbered}

*The learning goals may be adjusted before we start the material of this section.*

**EDA**

-   stuff

<br>

**Text Analysis**

-   stuff

<br>


### Project Presentations & Communication {.unnumbered}

*The learning goals may be adjusted before we start the material of this section.*

**Oral Communication**

-   stuff

<br>

**Written Communication**

-   stuff 

<br>